version: '3.8'

services:
  motion-api:
    build: .
    container_name: motion-video-api
    runtime: nvidia
    network_mode: host
    environment:
      - COMFYUI_HOST=127.0.0.1
      - COMFYUI_PORT=9188
    volumes:
      - ./output:/app/output
      - ./workflows:/app/workflows
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
