version: '3.8'

services:
  motion-api:
    build: .
    container_name: motion-video-api
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - CUDA_VISIBLE_DEVICES=0
      - COMFYUI_HOST=localhost
      - COMFYUI_PORT=9188
    ports:
      - "9000:9000"  # API service
      - "9188:9188"  # ComfyUI (optional, for debugging)
    volumes:
      - ./models:/app/ComfyUI/models
      - ./custom_nodes:/app/ComfyUI/custom_nodes
      - ./output:/app/output
      - ./input:/app/ComfyUI/input
      - ./workflows:/app/workflows
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s